// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ARUNK2121/procast/pkg/api"
	"github.com/ARUNK2121/procast/pkg/api/handler/admin"
	"github.com/ARUNK2121/procast/pkg/api/handler/provider"
	"github.com/ARUNK2121/procast/pkg/api/handler/user"
	"github.com/ARUNK2121/procast/pkg/config"
	"github.com/ARUNK2121/procast/pkg/db"
	"github.com/ARUNK2121/procast/pkg/helper"
	"github.com/ARUNK2121/procast/pkg/repository/admin"
	"github.com/ARUNK2121/procast/pkg/repository/provider"
	"github.com/ARUNK2121/procast/pkg/repository/user"
	"github.com/ARUNK2121/procast/pkg/usecase/admin"
	"github.com/ARUNK2121/procast/pkg/usecase/provider"
	"github.com/ARUNK2121/procast/pkg/usecase/user"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*httpserver.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := adminrepository.NewAdminRepository(gormDB)
	interfacesHelper := helper.NewHelper(cfg)
	adminUsecase := adminusecase.NewAdminUsecase(adminRepository, interfacesHelper)
	adminHandler := adminhandler.NewAdminHandler(adminUsecase)
	categoryRepository := adminrepository.NewCategoryRepository(gormDB)
	categoryUsecase := adminusecase.NewCategoryUsecase(categoryRepository)
	categoryHandler := adminhandler.NewCategoryHandler(categoryUsecase)
	serviceRepository := adminrepository.NewServiceRepository(gormDB)
	userManagementRepository := adminrepository.NewUserManagementRepository(gormDB)
	regionRepository := adminrepository.NewRegionRepository(gormDB)
	serviceUsecase := adminusecase.NewServiceUsecase(serviceRepository, userManagementRepository, regionRepository)
	serviceHandler := adminhandler.NewServiceHandler(serviceUsecase)
	regionUsecase := adminusecase.NewRegionUsecase(regionRepository)
	regionHandler := adminhandler.NewRegionHandler(regionUsecase)
	userManagementUsecase := adminusecase.NewUserManagementUsecase(userManagementRepository, serviceRepository)
	userManagementHandler := adminhandler.NewUserManagementHandler(userManagementUsecase)
	authenticationRepository := providerRepository.NewAuthenticationRepository(gormDB)
	authenticationUsecase := providerusecase.NewAuthenticationUsecase(authenticationRepository, interfacesHelper)
	authenticationHandler := providerhandler.NewAuthenticationHandler(authenticationUsecase)
	profileRepository := providerRepository.NewProfileRepository(gormDB)
	profileUsecase := providerusecase.NewProfileUsecase(profileRepository)
	profileHandler := providerhandler.NewProfileHandler(profileUsecase)
	workRepository := providerRepository.NewWorkRepository(gormDB)
	workUseCase := providerusecase.NewWorkUseCase(workRepository, profileRepository)
	workHandler := providerhandler.NewWorkHandler(workUseCase)
	notificationRepository := providerRepository.NewNotificationRepository(gormDB)
	notificationUsecase := providerusecase.NewNotificationUsecase(notificationRepository)
	notificationHandler := providerhandler.NewNotificationHandler(notificationUsecase)
	interfacesAuthenticationRepository := user_repository.NewAuthenticationRepository(gormDB)
	interfacesAuthenticationUsecase := userusecase.NewAuthenticationUsecase(interfacesAuthenticationRepository, interfacesHelper)
	userhandlerAuthenticationHandler := userhandler.NewAuthenticationHandler(interfacesAuthenticationUsecase)
	serverHTTP := httpserver.NewServerHTTP(adminHandler, categoryHandler, serviceHandler, regionHandler, userManagementHandler, authenticationHandler, profileHandler, workHandler, notificationHandler, userhandlerAuthenticationHandler)
	return serverHTTP, nil
}
