name: Procast CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0  # Replace with your Go version

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag arunkarun/procast:$(date +%s)

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push arunkarun/procast:$(date +%s)

      - name: Clean up
        run: docker image prune -f
